# AdvancedPets by GC
# Version: 1.1.3
# Release date: 2022/03/04

# Wiki: https://pets.advancedplugins.net

settings:
  language: en

# Sound list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sounds:
  # Sound played when GUI item is clicked
  uiClick: 'UI_BUTTON_CLICK'
  # Played when owned pet is right-clicked
  petRightClick: 'ENTITY_SHULKER_OPEN'


# Permission to rename pets: advancedpets.rename
petRenaming:
  useColors: true # Should players be able to use color codes? Permission: advancedpets.rename.colors
  maximumLength: 32
  blockSwearWords: true # Should bad words be blocked automatically?
  wordBlacklist: # Swear word filter is built-in
    - 'badWord1'
    - 'badWord2'

# Should last active pet automatically spawn when player joins?
spawnPetUponJoining: true
